#pragma once

#define CONNECTION_STATUS_INIT_DELAY 7499
#define CONNECTION_STATUS_PROBE_DELAY 1249

layer_state_t layer_state_set_connection_layer_os_swap_status(layer_state_t state);
bool process_detected_host_os_connection_layer_os_swap_status(os_variant_t detected_os);
void housekeeping_task_connection_layer_os_swap_status(void);