#define USB_SUSPEND_WAKEUP_DELAY 0
#define SERIAL_NUMBER "XYZDP/lbjWPM"
#define LAYER_STATE_32BIT

#define MOUSE_EXTENDED_REPORT

#define NAVIGATOR_SCROLL_DIVIDER 24

#define POINTING_DEVICE_AUTO_MOUSE_ENABLE
#define AUTO_MOUSE_DEFAULT_LAYER 21
#define AUTO_MOUSE_THRESHOLD 10
#define AUTO_MOUSE_SCROLL_THRESHOLD AUTO_MOUSE_THRESHOLD / NAVIGATOR_SCROLL_DIVIDER


#define RGB_MATRIX_STARTUP_SPD 60

