#define USB_SUSPEND_WAKEUP_DELAY 0
#define SERIAL_NUMBER "XYZDP/RjyNnb"
#define LAYER_STATE_32BIT

#define AUTOMOUSE_LAYER 2
#define AUTOMOUSE_TIMEOUT 651
#define AUTOMOUSE_THRESHOLD 0
#define AUTOMOUSE_SCROLL_THRESHOLD 30000

#define RGB_MATRIX_STARTUP_SPD 60

// must use 16bit extended report for sub_trackball
#define MOUSE_EXTENDED_REPORT
#define WHEEL_EXTENDED_REPORT

#define POINTING_DEVICE_HIRES_SCROLL_ENABLE
#define POINTING_DEVICE_HIRES_SCROLL_MULTIPLIER 120
#define POINTING_DEVICE_HIRES_SCROLL_EXPONENT 0

// wait sensor update (on matrix_scan) & 125 fps target 
#define POINTING_DEVICE_TASK_THROTTLE_MS 8

// #define NAVIGATOR_TRACKBALL_ROTATION 1
// #define NAVIGATOR_TRACKPAD_ROTATION 359

// more short timeout, normal 100
// on voyager/config.h  
// #define MCP23018_TIMEOUT 10
// #define IS31FL3731_I2C_TIMEOUT 5
// use dafaults for safe, non effective
//#define VOYAGER_I2C_TIMEOUT 10
//#define IS31FL3731_I2C_TIMEOUT 25 
//#define NAVIGATOR_TRACKBALL_TIMEOUT 10
//#define NAVIGATOR_TRACKPAD_TIMEOUT 10

#undef USB_SUSPEND_WAKEUP_DELAY
#define USB_SUSPEND_WAKEUP_DELAY 1999

#define USB_POLLING_INTERVAL_MS 1

#undef DEBOUNCE
#define DEBOUNCE 8

#define NKRO_DEFAULT_ON true

#define MOUSE_JIGGLER_INTERVAL_MS 6007
#define MOUSE_JIGGLER_MOVEMENT 1

#define MOONLANDER_USER_LED
#define VOYAGER_USER_LED

#define MOONLANDER_USER_LEDS
#define VOYAGER_USER_LEDS

//#define MAX_DEFERRED_EXECUTORS 16

// near max value
#define OS_DETECTION_DEBOUNCE 1999
//#define OS_DETECTION_KEYBOARD_RESET
//#define OS_DETECTION_SINGLE_REPORT

//#define LAYER_LOCK_IDLE_TIMEOUT 59999

#undef TAPPING_TERM
#define TAPPING_TERM 293

#define FLOW_TAP_TERM 199

#undef ONESHOT_TIMEOUT
#define ONESHOT_TIMEOUT 7993

//#undef ONESHOT_TAP_TOGGLE
//#define ONESHOT_TAP_TOGGLE 5  

#undef USE_CIE1931_CURVE
#define USE_CIE1931_CURVE

#undef IS31FL3731_DEGHOST
#define IS31FL3731_DEGHOST

// user impl RGB timeout, disable system side
#undef RGB_MATRIX_TIMEOUT
#define RGB_MATRIX_TIMEOUT 0
#undef RGB_DISABLE_WHEN_USB_SUSPENDED
#undef RGB_MATRIX_SLEEP
#undef LED_MATRIX_SLEEP

// RAM eeprom minimal safety size
#define TRANSIENT_EEPROM_SIZE 512

#undef ENABLE_RGB_MATRIX_ALPHAS_MODS
#undef ENABLE_RGB_MATRIX_GRADIENT_UP_DOWN
#undef ENABLE_RGB_MATRIX_GRADIENT_LEFT_RIGHT
//#undef ENABLE_RGB_MATRIX_BREATHING
#undef ENABLE_RGB_MATRIX_BAND_SAT
#undef ENABLE_RGB_MATRIX_BAND_VAL
#undef ENABLE_RGB_MATRIX_BAND_PINWHEEL_SAT
#undef ENABLE_RGB_MATRIX_BAND_PINWHEEL_VAL
#undef ENABLE_RGB_MATRIX_BAND_SPIRAL_SAT
#undef ENABLE_RGB_MATRIX_BAND_SPIRAL_VAL
#undef ENABLE_RGB_MATRIX_CYCLE_ALL
//#undef ENABLE_RGB_MATRIX_CYCLE_LEFT_RIGHT
#undef ENABLE_RGB_MATRIX_CYCLE_UP_DOWN
#undef ENABLE_RGB_MATRIX_CYCLE_OUT_IN
#undef ENABLE_RGB_MATRIX_CYCLE_OUT_IN_DUAL
#undef ENABLE_RGB_MATRIX_RAINBOW_MOVING_CHEVRON
#undef ENABLE_RGB_MATRIX_CYCLE_PINWHEEL
#undef ENABLE_RGB_MATRIX_CYCLE_SPIRAL
#undef ENABLE_RGB_MATRIX_DUAL_BEACON
#undef ENABLE_RGB_MATRIX_RAINBOW_BEACON
#undef ENABLE_RGB_MATRIX_RAINBOW_PINWHEELS
//#undef ENABLE_RGB_MATRIX_FLOWER_BLOOMING
#undef ENABLE_RGB_MATRIX_RAINDROPS
#undef ENABLE_RGB_MATRIX_JELLYBEAN_RAINDROPS
#undef ENABLE_RGB_MATRIX_HUE_BREATHING
#undef ENABLE_RGB_MATRIX_HUE_PENDULUM
#undef ENABLE_RGB_MATRIX_HUE_WAVE
#undef ENABLE_RGB_MATRIX_PIXEL_FRACTAL
#undef ENABLE_RGB_MATRIX_PIXEL_FLOW
#undef ENABLE_RGB_MATRIX_PIXEL_RAIN
#undef ENABLE_RGB_MATRIX_TYPING_HEATMAP
#undef ENABLE_RGB_MATRIX_DIGITAL_RAIN
#undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_SIMPLE
#undef ENABLE_RGB_MATRIX_SOLID_REACTIVE
#undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_WIDE
#undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTIWIDE
#undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_CROSS
#undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTICROSS
#undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_NEXUS
#undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTINEXUS
#undef ENABLE_RGB_MATRIX_SPLASH
#undef ENABLE_RGB_MATRIX_MULTISPLASH
#undef ENABLE_RGB_MATRIX_SOLID_SPLASH
#undef ENABLE_RGB_MATRIX_SOLID_MULTISPLASH
#undef ENABLE_RGB_MATRIX_STARLIGHT
#undef ENABLE_RGB_MATRIX_STARLIGHT_DUAL_HUE
#undef ENABLE_RGB_MATRIX_STARLIGHT_DUAL_SAT
#undef ENABLE_RGB_MATRIX_RIVERFLOW

