#include QMK_KEYBOARD_H
#include "version.h"
#define MOON_LED_LEVEL LED_LEVEL
#ifndef ZSA_SAFE_RANGE
#define ZSA_SAFE_RANGE SAFE_RANGE
#endif

enum custom_keycodes {
  RGB_SLD = ZSA_SAFE_RANGE,
};




const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
  [0] = LAYOUT_voyager(
    MT(MOD_LALT | MOD_LSFT | MOD_LCTL, KC_A),MT(MOD_LALT | MOD_LSFT | MOD_LCTL, KC_B),MT(MOD_LCTL, KC_Y),MT(MOD_LCTL, KC_O),MT(MOD_LCTL, KC_U),MT(MOD_LALT | MOD_LSFT | MOD_LCTL, KC_C),                                MT(MOD_LALT | MOD_LSFT | MOD_LCTL, KC_G),MT(MOD_LCTL, KC_D),MT(MOD_LCTL, KC_N),MT(MOD_LCTL, KC_G),MT(MOD_LALT | MOD_LSFT | MOD_LCTL, KC_F),CW_TOGG,        
    MT(MOD_LCTL, KC_B),MT(MOD_LCTL, KC_H),MT(MOD_LCTL, KC_I),MT(MOD_LCTL, KC_A),MT(MOD_LCTL, KC_E),MT(MOD_LALT | MOD_LSFT | MOD_LCTL, KC_D),                                MT(MOD_LALT | MOD_LSFT | MOD_LCTL, KC_H),MT(MOD_LCTL, KC_T),MT(MOD_LCTL, KC_R),MT(MOD_LCTL, KC_S),MT(MOD_LCTL, KC_C),MT(MOD_LCTL, KC_V),
    MT(MOD_LCTL, KC_Q),MT(MOD_LCTL, KC_K),MT(MOD_LCTL, KC_J),MT(MOD_LCTL, KC_X),MT(MOD_LCTL, KC_W),MT(MOD_LALT | MOD_LSFT | MOD_LCTL, KC_E),                                MT(MOD_LALT | MOD_LSFT | MOD_LCTL, KC_I),MT(MOD_LCTL, KC_M),MT(MOD_LCTL, KC_L),MT(MOD_LCTL, KC_F),MT(MOD_LCTL, KC_P),MT(MOD_LCTL, KC_Z),
    KC_LEFT_SHIFT,  KC_LEFT,        KC_RIGHT,       KC_BSPC,        MT(MOD_LCTL, KC_SPACE),KC_NO,                                          KC_NO,          MT(MOD_LCTL, KC_SPACE),MT(MOD_LCTL, KC_DELETE),KC_UP,          KC_DOWN,        KC_RIGHT_SHIFT, 
                                                    MT(MOD_LCTL, KC_TAB),MT(MOD_LCTL, KC_ESCAPE),                                MT(MOD_LCTL, KC_BSPC),KC_ENTER
  ),
  [1] = LAYOUT_voyager(
    KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT,                                 KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, 
    KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT,                                 KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, 
    KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT,                                 KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, 
    KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT,                                 KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, 
                                                    KC_TRANSPARENT, KC_TRANSPARENT,                                 KC_TRANSPARENT, KC_TRANSPARENT
  ),
  [2] = LAYOUT_voyager(
    LGUI(KC_TAB),   KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT,                                 KC_MS_BTN4,     KC_MS_BTN2,     KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, 
    MO(9),          KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_MS_BTN4,                                     KC_MS_BTN3,     KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, MO(10),         
    KC_LEFT_CTRL,   KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_MS_BTN3,                                     KC_MS_BTN1,     KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_RIGHT_CTRL,  
    KC_LEFT_SHIFT,  KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, MO(3),          KC_TRANSPARENT,                                 KC_TRANSPARENT, MO(4),          KC_TRANSPARENT, NAVIGATOR_DEC_CPI,NAVIGATOR_INC_CPI,KC_RIGHT_SHIFT, 
                                                    KC_MS_BTN2,     KC_MS_BTN1,                                     KC_TRANSPARENT, KC_TRANSPARENT
  ),
  [3] = LAYOUT_voyager(
    CW_TOGG,        KC_TRANSPARENT, MT(MOD_LALT | MOD_LSFT | MOD_LCTL, KC_COMMA),MT(MOD_LALT | MOD_LSFT | MOD_LCTL, KC_DOT),MT(MOD_LALT | MOD_LSFT | MOD_LCTL, KC_6),MT(MOD_RALT | MOD_RSFT | MOD_RCTL, KC_6),                                MT(MOD_RALT | MOD_RSFT | MOD_RCTL, KC_5),MT(MOD_LALT | MOD_LSFT | MOD_LCTL, KC_5),MT(MOD_LALT | MOD_LSFT | MOD_LCTL, KC_COMMA),MT(MOD_LALT | MOD_LSFT | MOD_LCTL, KC_DOT),KC_TRANSPARENT, KC_TRANSPARENT, 
    MT(MOD_LALT | MOD_LSFT | MOD_LCTL, KC_L),MT(MOD_LALT | MOD_LSFT | MOD_LCTL, KC_1),MT(MOD_LALT | MOD_LSFT | MOD_LCTL, KC_2),MT(MOD_LALT | MOD_LSFT | MOD_LCTL, KC_3),MT(MOD_LALT | MOD_LSFT | MOD_LCTL, KC_4),MT(MOD_LALT | MOD_LSFT | MOD_LCTL, KC_5),                                MT(MOD_LALT | MOD_LSFT | MOD_LCTL, KC_6),MT(MOD_LALT | MOD_LSFT | MOD_LCTL, KC_7),MT(MOD_LALT | MOD_LSFT | MOD_LCTL, KC_8),MT(MOD_LALT | MOD_LSFT | MOD_LCTL, KC_9),MT(MOD_LALT | MOD_LSFT | MOD_LCTL, KC_0),MT(MOD_LALT | MOD_LSFT | MOD_LCTL, KC_R),
    MT(MOD_RALT | MOD_RSFT | MOD_RCTL, KC_L),MT(MOD_RALT | MOD_RSFT | MOD_RCTL, KC_1),MT(MOD_RALT | MOD_RSFT | MOD_RCTL, KC_2),MT(MOD_RALT | MOD_RSFT | MOD_RCTL, KC_3),MT(MOD_RALT | MOD_RSFT | MOD_RCTL, KC_4),MT(MOD_RALT | MOD_RSFT | MOD_RCTL, KC_5),                                MT(MOD_RALT | MOD_RSFT | MOD_RCTL, KC_6),MT(MOD_RALT | MOD_RSFT | MOD_RCTL, KC_7),MT(MOD_RALT | MOD_RSFT | MOD_RCTL, KC_8),MT(MOD_RALT | MOD_RSFT | MOD_RCTL, KC_9),MT(MOD_RALT | MOD_RSFT | MOD_RCTL, KC_0),MT(MOD_RALT | MOD_RSFT | MOD_RCTL, KC_R),
    KC_TRANSPARENT, KC_MEDIA_STOP,  KC_MEDIA_PLAY_PAUSE,KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT,                                 KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_AUDIO_VOL_DOWN,KC_AUDIO_VOL_UP,KC_AUDIO_MUTE,  
                                                    KC_TRANSPARENT, KC_TRANSPARENT,                                 KC_TRANSPARENT, KC_TRANSPARENT
  ),
  [4] = LAYOUT_voyager(
    CW_TOGG,        KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, MT(MOD_RALT | MOD_RSFT | MOD_RCTL, KC_C),                                MT(MOD_RALT | MOD_RSFT | MOD_RCTL, KC_G),LCTL(KC_V),     KC_UP,          LCTL(KC_C),     KC_APPLICATION, KC_BSPC,        
    MO(9),          MT(MOD_LGUI | MOD_LSFT | MOD_LCTL, KC_A),MT(MOD_LGUI | MOD_LSFT | MOD_LCTL, KC_B),MT(MOD_LGUI | MOD_LSFT | MOD_LCTL, KC_C),MT(MOD_LGUI | MOD_LSFT | MOD_LCTL, KC_D),MT(MOD_RALT | MOD_RSFT | MOD_RCTL, KC_D),                                MT(MOD_RALT | MOD_RSFT | MOD_RCTL, KC_H),KC_LEFT,        KC_DOWN,        KC_RIGHT,       KC_DELETE,      MO(10),         
    KC_LEFT_CTRL,   MT(MOD_LGUI | MOD_LSFT | MOD_LCTL, KC_E),MT(MOD_LGUI | MOD_LSFT | MOD_LCTL, KC_F),MT(MOD_LGUI | MOD_LSFT | MOD_LCTL, KC_G),MT(MOD_LGUI | MOD_LSFT | MOD_LCTL, KC_H),MT(MOD_RALT | MOD_RSFT | MOD_RCTL, KC_E),                                MT(MOD_RALT | MOD_RSFT | MOD_RCTL, KC_I),MT(MOD_LGUI | MOD_LSFT | MOD_LCTL, KC_I),MT(MOD_LGUI | MOD_LSFT | MOD_LCTL, KC_J),MT(MOD_LGUI | MOD_LSFT | MOD_LCTL, KC_K),MT(MOD_LGUI | MOD_LSFT | MOD_LCTL, KC_L),KC_RIGHT_CTRL,  
    KC_TRANSPARENT, KC_MEDIA_PREV_TRACK,KC_MEDIA_NEXT_TRACK,KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT,                                 KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_BRIGHTNESS_DOWN,KC_BRIGHTNESS_UP,KC_TRANSPARENT, 
                                                    KC_TRANSPARENT, KC_TRANSPARENT,                                 KC_TRANSPARENT, KC_TRANSPARENT
  ),
  [5] = LAYOUT_voyager(
    CW_TOGG,        KC_F21,         KC_F22,         MT(MOD_LALT | MOD_LSFT, KC_F23),MT(MOD_LALT | MOD_LCTL, KC_F24),KC_TRANSPARENT,                                 KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, 
    LT(9, KC_F11),  MT(MOD_LSFT | MOD_LCTL, KC_F1),MT(MOD_LGUI | MOD_LALT, KC_F2),MT(MOD_LSFT, KC_F3),MT(MOD_LCTL, KC_F4),MT(MOD_LGUI | MOD_LSFT | MOD_LCTL, KC_F5),                                MT(MOD_RGUI | MOD_RSFT | MOD_RCTL, KC_F6),MT(MOD_RCTL, KC_F7),MT(MOD_RSFT, KC_F8),MT(MOD_RGUI | MOD_RALT, KC_F9),MT(MOD_RSFT | MOD_RCTL, KC_F10),LT(10, KC_F12), 
    KC_LEFT_CTRL,   MT(MOD_LGUI, KC_F11),MT(MOD_LALT, KC_F12),MT(MOD_LGUI | MOD_LSFT, KC_F13),MT(MOD_LGUI | MOD_LCTL, KC_F14),MT(MOD_LALT | MOD_LGUI | MOD_LCTL, KC_F15),                                MT(MOD_RALT | MOD_RGUI | MOD_RCTL, KC_F16),MT(MOD_RGUI | MOD_RCTL, KC_F17),MT(MOD_RGUI | MOD_RSFT, KC_F18),MT(MOD_RALT, KC_F19),MT(MOD_RGUI, KC_F20),KC_RIGHT_CTRL,  
    KC_TRANSPARENT, KC_MEDIA_PREV_TRACK,KC_MEDIA_NEXT_TRACK,KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT,                                 KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_AUDIO_VOL_DOWN,KC_AUDIO_VOL_UP,KC_AUDIO_MUTE,  
                                                    KC_TRANSPARENT, KC_TRANSPARENT,                                 KC_TRANSPARENT, KC_TRANSPARENT
  ),
  [6] = LAYOUT_voyager(
    KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT,                                 KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, 
    KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT,                                 KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, 
    KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT,                                 KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, 
    KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT,                                 KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, 
                                                    KC_TRANSPARENT, KC_TRANSPARENT,                                 KC_TRANSPARENT, KC_TRANSPARENT
  ),
  [7] = LAYOUT_voyager(
    KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT,                                 KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, 
    KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT,                                 KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, 
    KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT,                                 KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, 
    KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT,                                 KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, 
                                                    KC_TRANSPARENT, KC_TRANSPARENT,                                 KC_TRANSPARENT, KC_TRANSPARENT
  ),
  [8] = LAYOUT_voyager(
    KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT,                                 KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, 
    KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT,                                 KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, 
    KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT,                                 KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, 
    KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT,                                 KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, 
                                                    KC_TRANSPARENT, KC_TRANSPARENT,                                 KC_TRANSPARENT, KC_TRANSPARENT
  ),
  [9] = LAYOUT_voyager(
    KC_TRANSPARENT, LCTL(KC_Q),     LCTL(KC_W),     LCTL(KC_E),     LCTL(KC_R),     LCTL(KC_T),                                     LCTL(KC_Y),     LCTL(KC_U),     LCTL(KC_I),     LCTL(KC_O),     LCTL(KC_P),     KC_TRANSPARENT, 
    KC_TRANSPARENT, LCTL(KC_A),     LCTL(KC_S),     LCTL(KC_D),     LCTL(KC_F),     LCTL(KC_G),                                     LCTL(KC_H),     LCTL(KC_J),     LCTL(KC_K),     LCTL(KC_L),     KC_TRANSPARENT, KC_TRANSPARENT, 
    KC_TRANSPARENT, LCTL(KC_Z),     LCTL(KC_X),     LCTL(KC_C),     LCTL(KC_V),     LCTL(KC_B),                                     LCTL(KC_N),     LCTL(KC_M),     LCTL(KC_COMMA), LCTL(KC_DOT),   KC_TRANSPARENT, KC_TRANSPARENT, 
    KC_TRANSPARENT, RGB_HUD,        RGB_HUI,        KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT,                                 KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, RGB_SAD,        RGB_SAI,        KC_TRANSPARENT, 
                                                    KC_TRANSPARENT, KC_TRANSPARENT,                                 KC_TRANSPARENT, KC_TRANSPARENT
  ),
  [10] = LAYOUT_voyager(
    KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT,                                 KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, 
    KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT,                                 KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, 
    KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT,                                 KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, 
    KC_TRANSPARENT, RGB_VAD,        RGB_VAI,        KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT,                                 KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, RGB_TOG,        RGB_MODE_FORWARD,KC_TRANSPARENT, 
                                                    KC_TRANSPARENT, KC_TRANSPARENT,                                 KC_TRANSPARENT, KC_TRANSPARENT
  ),
  [11] = LAYOUT_voyager(
    KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT,                                 KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, 
    KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT,                                 KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, 
    KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT,                                 KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, 
    KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT,                                 KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, 
                                                    KC_TRANSPARENT, KC_TRANSPARENT,                                 KC_TRANSPARENT, KC_TRANSPARENT
  ),
  [12] = LAYOUT_voyager(
    KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT,                                 KC_TRANSPARENT, LGUI(LSFT(KC_R)),KC_PSCR,        KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, 
    KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT,                                 KC_TRANSPARENT, LGUI(LSFT(KC_S)),LALT(KC_PSCR),  KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, 
    KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT,                                 KC_TRANSPARENT, LGUI(LSFT(KC_T)),LGUI(KC_PSCR),  KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, 
    KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT,                                 KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, 
                                                    KC_TRANSPARENT, KC_TRANSPARENT,                                 KC_TRANSPARENT, KC_TRANSPARENT
  ),
  [13] = LAYOUT_voyager(
    KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT,                                 KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, 
    KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT,                                 KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, 
    KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT,                                 KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, 
    KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT,                                 KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, RGB_SPD,        RGB_SPI,        RGB_SLD,        
                                                    KC_TRANSPARENT, KC_TRANSPARENT,                                 KC_TRANSPARENT, KC_TRANSPARENT
  ),
  [14] = LAYOUT_voyager(
    KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT,                                 KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, 
    KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT,                                 KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, 
    KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT,                                 KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, 
    KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT,                                 KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, 
                                                    KC_TRANSPARENT, KC_TRANSPARENT,                                 KC_TRANSPARENT, KC_TRANSPARENT
  ),
  [15] = LAYOUT_voyager(
    KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT,                                 KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, 
    KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT,                                 KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, 
    KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT,                                 KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, 
    KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT,                                 KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, 
                                                    KC_TRANSPARENT, KC_TRANSPARENT,                                 KC_TRANSPARENT, KC_TRANSPARENT
  ),
  [16] = LAYOUT_voyager(
    CW_TOGG,        MT(MOD_RALT | MOD_RGUI | MOD_RSFT | MOD_RCTL, KC_M),MT(MOD_RALT | MOD_RGUI | MOD_RSFT | MOD_RCTL, KC_M),MT(MOD_RALT | MOD_RGUI | MOD_RSFT | MOD_RCTL, KC_M),MT(MOD_RALT | MOD_RGUI | MOD_RSFT | MOD_RCTL, KC_M),LGUI(LCTL(KC_V)),                                KC_ESCAPE,      KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, 
    KC_TRANSPARENT, MT(MOD_RALT | MOD_RGUI | MOD_RSFT | MOD_RCTL, KC_M),MT(MOD_RALT | MOD_RGUI | MOD_RSFT | MOD_RCTL, KC_M),MT(MOD_RALT | MOD_RGUI | MOD_RSFT | MOD_RCTL, KC_M),MT(MOD_RALT | MOD_RGUI | MOD_RSFT | MOD_RCTL, KC_M),LGUI(KC_V),                                     KC_TRANSPARENT, MT(MOD_RALT | MOD_RGUI | MOD_RSFT | MOD_RCTL, KC_M),MT(MOD_RALT | MOD_RGUI | MOD_RSFT | MOD_RCTL, KC_M),MT(MOD_RALT | MOD_RGUI | MOD_RSFT | MOD_RCTL, KC_M),MT(MOD_RALT | MOD_RGUI | MOD_RSFT | MOD_RCTL, KC_M),MT(MOD_RALT | MOD_RGUI | MOD_RSFT | MOD_RCTL, KC_M),
    KC_LEFT_CTRL,   MT(MOD_LGUI | MOD_LSFT | MOD_LCTL, KC_M),MT(MOD_LGUI | MOD_LSFT | MOD_LCTL, KC_N),MT(MOD_RALT | MOD_RGUI | MOD_RSFT | MOD_RCTL, KC_M),MT(MOD_RALT | MOD_RGUI | MOD_RSFT | MOD_RCTL, KC_M),LGUI(LSFT(KC_V)),                                KC_BSPC,        MT(MOD_RGUI | MOD_RSFT | MOD_RCTL, KC_I),MT(MOD_RGUI | MOD_RSFT | MOD_RCTL, KC_J),MT(MOD_RGUI | MOD_RSFT | MOD_RCTL, KC_K),MT(MOD_RGUI | MOD_RSFT | MOD_RCTL, KC_L),KC_RIGHT_CTRL,  
    KC_TRANSPARENT, KC_MEDIA_REWIND,KC_MEDIA_FAST_FORWARD,KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT,                                 KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_BRIGHTNESS_DOWN,KC_BRIGHTNESS_UP,KC_TRANSPARENT, 
                                                    KC_TRANSPARENT, KC_TRANSPARENT,                                 KC_TRANSPARENT, KC_TRANSPARENT
  ),
  [17] = LAYOUT_voyager(
    KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT,                                 KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, 
    KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_MS_BTN8,                                     KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, 
    KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_MS_BTN7,                                     KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, 
    KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT,                                 KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, 
                                                    KC_MS_BTN6,     KC_MS_BTN5,                                     KC_TRANSPARENT, KC_TRANSPARENT
  ),
  [18] = LAYOUT_voyager(
    KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT,                                 KC_MS_BTN8,     KC_MS_BTN6,     KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, 
    KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT,                                 KC_MS_BTN7,     KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, 
    KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT,                                 KC_MS_BTN5,     KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, 
    KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT,                                 KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, 
                                                    KC_TRANSPARENT, KC_TRANSPARENT,                                 KC_TRANSPARENT, KC_TRANSPARENT
  ),
  [19] = LAYOUT_voyager(
    MT(MOD_RALT | MOD_RGUI | MOD_RSFT | MOD_RCTL, KC_1),MT(MOD_RALT | MOD_RGUI | MOD_RSFT | MOD_RCTL, KC_1),MT(MOD_RALT | MOD_RGUI | MOD_RSFT | MOD_RCTL, KC_1),MT(MOD_RALT | MOD_RGUI | MOD_RSFT | MOD_RCTL, KC_1),MT(MOD_RALT | MOD_RGUI | MOD_RSFT | MOD_RCTL, KC_1),MT(MOD_RALT | MOD_RGUI | MOD_RSFT | MOD_RCTL, KC_1),                                MT(MOD_RALT | MOD_RGUI | MOD_RSFT | MOD_RCTL, KC_1),MT(MOD_RALT | MOD_RGUI | MOD_RSFT | MOD_RCTL, KC_1),MT(MOD_RALT | MOD_RGUI | MOD_RSFT | MOD_RCTL, KC_1),MT(MOD_RALT | MOD_RGUI | MOD_RSFT | MOD_RCTL, KC_1),MT(MOD_RALT | MOD_RGUI | MOD_RSFT | MOD_RCTL, KC_1),MT(MOD_RALT | MOD_RGUI | MOD_RSFT | MOD_RCTL, KC_1),
    MT(MOD_RALT | MOD_RGUI | MOD_RSFT | MOD_RCTL, KC_1),MT(MOD_RALT | MOD_RGUI | MOD_RSFT | MOD_RCTL, KC_1),MT(MOD_RALT | MOD_RGUI | MOD_RSFT | MOD_RCTL, KC_1),MT(MOD_RALT | MOD_RGUI | MOD_RSFT | MOD_RCTL, KC_1),MT(MOD_RALT | MOD_RGUI | MOD_RSFT | MOD_RCTL, KC_1),MT(MOD_RALT | MOD_RGUI | MOD_RSFT | MOD_RCTL, KC_1),                                MT(MOD_RALT | MOD_RGUI | MOD_RSFT | MOD_RCTL, KC_1),MT(MOD_RALT | MOD_RGUI | MOD_RSFT | MOD_RCTL, KC_1),MT(MOD_RALT | MOD_RGUI | MOD_RSFT | MOD_RCTL, KC_1),MT(MOD_RALT | MOD_RGUI | MOD_RSFT | MOD_RCTL, KC_1),MT(MOD_RALT | MOD_RGUI | MOD_RSFT | MOD_RCTL, KC_1),MT(MOD_RALT | MOD_RGUI | MOD_RSFT | MOD_RCTL, KC_1),
    MT(MOD_RALT | MOD_RGUI | MOD_RSFT | MOD_RCTL, KC_1),MT(MOD_RALT | MOD_RGUI | MOD_RSFT | MOD_RCTL, KC_1),MT(MOD_RALT | MOD_RGUI | MOD_RSFT | MOD_RCTL, KC_1),MT(MOD_RALT | MOD_RGUI | MOD_RSFT | MOD_RCTL, KC_1),MT(MOD_RALT | MOD_RGUI | MOD_RSFT | MOD_RCTL, KC_1),MT(MOD_RALT | MOD_RGUI | MOD_RSFT | MOD_RCTL, KC_1),                                MT(MOD_RALT | MOD_RGUI | MOD_RSFT | MOD_RCTL, KC_1),MT(MOD_RALT | MOD_RGUI | MOD_RSFT | MOD_RCTL, KC_1),MT(MOD_RALT | MOD_RGUI | MOD_RSFT | MOD_RCTL, KC_1),MT(MOD_RALT | MOD_RGUI | MOD_RSFT | MOD_RCTL, KC_1),MT(MOD_RALT | MOD_RGUI | MOD_RSFT | MOD_RCTL, KC_1),MT(MOD_RALT | MOD_RGUI | MOD_RSFT | MOD_RCTL, KC_1),
    KC_LEFT_SHIFT,  KC_CAPS,        KC_NO,          MT(MOD_RALT | MOD_RGUI | MOD_RSFT | MOD_RCTL, KC_1),KC_NO,          MT(MOD_RALT | MOD_RGUI | MOD_RSFT | MOD_RCTL, KC_3),                                KC_NUM,         KC_SCRL,        KC_NO,          MT(MOD_RALT | MOD_RGUI | MOD_RSFT | MOD_RCTL, KC_1),MT(MOD_RALT | MOD_RGUI | MOD_RSFT | MOD_RCTL, KC_1),MT(MOD_RALT | MOD_RGUI | MOD_RSFT | MOD_RCTL, KC_1),
                                                    KC_TRANSPARENT, KC_TRANSPARENT,                                 MT(MOD_RALT | MOD_RGUI | MOD_RSFT | MOD_RCTL, KC_2),MT(MOD_RALT | MOD_RGUI | MOD_RSFT | MOD_RCTL, KC_3)
  ),
  [20] = LAYOUT_voyager(
    MT(MOD_RALT | MOD_RGUI | MOD_RSFT | MOD_RCTL, KC_4),MT(MOD_RALT | MOD_RGUI | MOD_RSFT | MOD_RCTL, KC_4),MT(MOD_RALT | MOD_RGUI | MOD_RSFT | MOD_RCTL, KC_4),MT(MOD_RALT | MOD_RGUI | MOD_RSFT | MOD_RCTL, KC_4),MT(MOD_RALT | MOD_RGUI | MOD_RSFT | MOD_RCTL, KC_4),MT(MOD_RALT | MOD_RGUI | MOD_RSFT | MOD_RCTL, KC_4),                                MT(MOD_RALT | MOD_RGUI | MOD_RSFT | MOD_RCTL, KC_4),MT(MOD_RALT | MOD_RGUI | MOD_RSFT | MOD_RCTL, KC_4),MT(MOD_RALT | MOD_RGUI | MOD_RSFT | MOD_RCTL, KC_4),MT(MOD_RALT | MOD_RGUI | MOD_RSFT | MOD_RCTL, KC_4),MT(MOD_RALT | MOD_RGUI | MOD_RSFT | MOD_RCTL, KC_4),MT(MOD_RALT | MOD_RGUI | MOD_RSFT | MOD_RCTL, KC_4),
    MT(MOD_RALT | MOD_RGUI | MOD_RSFT | MOD_RCTL, KC_4),MT(MOD_RALT | MOD_RGUI | MOD_RSFT | MOD_RCTL, KC_4),MT(MOD_RALT | MOD_RGUI | MOD_RSFT | MOD_RCTL, KC_4),MT(MOD_RALT | MOD_RGUI | MOD_RSFT | MOD_RCTL, KC_4),MT(MOD_RALT | MOD_RGUI | MOD_RSFT | MOD_RCTL, KC_4),MT(MOD_RALT | MOD_RGUI | MOD_RSFT | MOD_RCTL, KC_4),                                MT(MOD_RALT | MOD_RGUI | MOD_RSFT | MOD_RCTL, KC_4),MT(MOD_RALT | MOD_RGUI | MOD_RSFT | MOD_RCTL, KC_4),MT(MOD_RALT | MOD_RGUI | MOD_RSFT | MOD_RCTL, KC_4),MT(MOD_RALT | MOD_RGUI | MOD_RSFT | MOD_RCTL, KC_4),MT(MOD_RALT | MOD_RGUI | MOD_RSFT | MOD_RCTL, KC_4),MT(MOD_RALT | MOD_RGUI | MOD_RSFT | MOD_RCTL, KC_4),
    MT(MOD_RALT | MOD_RGUI | MOD_RSFT | MOD_RCTL, KC_4),MT(MOD_RALT | MOD_RGUI | MOD_RSFT | MOD_RCTL, KC_4),MT(MOD_RALT | MOD_RGUI | MOD_RSFT | MOD_RCTL, KC_4),MT(MOD_RALT | MOD_RGUI | MOD_RSFT | MOD_RCTL, KC_4),MT(MOD_RALT | MOD_RGUI | MOD_RSFT | MOD_RCTL, KC_4),MT(MOD_RALT | MOD_RGUI | MOD_RSFT | MOD_RCTL, KC_4),                                MT(MOD_RALT | MOD_RGUI | MOD_RSFT | MOD_RCTL, KC_4),MT(MOD_RALT | MOD_RGUI | MOD_RSFT | MOD_RCTL, KC_4),MT(MOD_RALT | MOD_RGUI | MOD_RSFT | MOD_RCTL, KC_4),MT(MOD_RALT | MOD_RGUI | MOD_RSFT | MOD_RCTL, KC_4),MT(MOD_RALT | MOD_RGUI | MOD_RSFT | MOD_RCTL, KC_4),MT(MOD_RALT | MOD_RGUI | MOD_RSFT | MOD_RCTL, KC_4),
    MT(MOD_RALT | MOD_RGUI | MOD_RSFT | MOD_RCTL, KC_4),MT(MOD_RALT | MOD_RGUI | MOD_RSFT | MOD_RCTL, KC_4),MT(MOD_RALT | MOD_RGUI | MOD_RSFT | MOD_RCTL, KC_4),MT(MOD_RALT | MOD_RGUI | MOD_RSFT | MOD_RCTL, KC_4),MT(MOD_RALT | MOD_RGUI | MOD_RSFT | MOD_RCTL, KC_4),MT(MOD_RALT | MOD_RGUI | MOD_RSFT | MOD_RCTL, KC_4),                                MT(MOD_RALT | MOD_RGUI | MOD_RSFT | MOD_RCTL, KC_4),MT(MOD_RALT | MOD_RGUI | MOD_RSFT | MOD_RCTL, KC_4),MT(MOD_RALT | MOD_RGUI | MOD_RSFT | MOD_RCTL, KC_4),MT(MOD_RALT | MOD_RGUI | MOD_RSFT | MOD_RCTL, KC_4),MT(MOD_RALT | MOD_RGUI | MOD_RSFT | MOD_RCTL, KC_4),MT(MOD_RALT | MOD_RGUI | MOD_RSFT | MOD_RCTL, KC_4),
                                                    MT(MOD_RALT | MOD_RGUI | MOD_RSFT | MOD_RCTL, KC_5),MT(MOD_RALT | MOD_RGUI | MOD_RSFT | MOD_RCTL, KC_6),                                MT(MOD_RALT | MOD_RGUI | MOD_RSFT | MOD_RCTL, KC_7),MT(MOD_RALT | MOD_RGUI | MOD_RSFT | MOD_RCTL, KC_8)
  ),
};









bool process_record_user(uint16_t keycode, keyrecord_t *record) {
  switch (keycode) {
  case QK_MODS ... QK_MODS_MAX:
    // Mouse and consumer keys (volume, media) with modifiers work inconsistently across operating systems,
    // this makes sure that modifiers are always applied to the key that was pressed.
    if (IS_MOUSE_KEYCODE(QK_MODS_GET_BASIC_KEYCODE(keycode)) || IS_CONSUMER_KEYCODE(QK_MODS_GET_BASIC_KEYCODE(keycode))) {
      if (record->event.pressed) {
        add_mods(QK_MODS_GET_MODS(keycode));
        send_keyboard_report();
        wait_ms(2);
        register_code(QK_MODS_GET_BASIC_KEYCODE(keycode));
        return false;
      } else {
        wait_ms(2);
        del_mods(QK_MODS_GET_MODS(keycode));
      }
    }
    break;

    case RGB_SLD:
      if (record->event.pressed) {
        rgblight_mode(1);
      }
      return false;
  }
  return true;
}
