#pragma once

#define OS_LCTL OSM(MOD_LCTL)
#define OS_LSFT OSM(MOD_LSFT)
#define OS_LALT OSM(MOD_LALT)
#define OS_LGUI OSM(MOD_LGUI)

#define OS_LCS OSM(MOD_LCTL | MOD_LSFT)
#define OS_LCA OSM(MOD_LCTL | MOD_LALT)
#define OS_LCG OSM(MOD_LCTL | MOD_LGUI)
#define OS_LSA OSM(MOD_LSFT | MOD_LALT)
#define OS_LSG OSM(MOD_LSFT | MOD_LGUI)
#define OS_LAG OSM(MOD_LALT | MOD_LGUI)

#define OS_LCSG OSM(MOD_LCTL | MOD_LSFT | MOD_LGUI)
#define OS_LCAG OSM(MOD_LCTL | MOD_LALT | MOD_LGUI)
#define OS_LSAG OSM(MOD_LSFT | MOD_LALT | MOD_LGUI)

#define OS_RCTL OSM(MOD_RCTL)
#define OS_RSFT OSM(MOD_RSFT)
#define OS_RALT OSM(MOD_RALT)
#define OS_RGUI OSM(MOD_RGUI)

#define OS_RCS OSM(MOD_RCTL | MOD_RSFT)
#define OS_RCA OSM(MOD_RCTL | MOD_RALT)
#define OS_RCG OSM(MOD_RCTL | MOD_RGUI)
#define OS_RSA OSM(MOD_RSFT | MOD_RALT)
#define OS_RSG OSM(MOD_RSFT | MOD_RGUI)
#define OS_RAG OSM(MOD_RALT | MOD_RGUI)

#define OS_RCSG OSM(MOD_RCTL | MOD_RSFT | MOD_RGUI)
#define OS_RCAG OSM(MOD_RCTL | MOD_RALT | MOD_RGUI)
#define OS_RSAG OSM(MOD_RSFT | MOD_RALT | MOD_RGUI)

#define OS_MEH OSM(MOD_LCTL | MOD_LSFT | MOD_LALT)
#define OS_HYPR OSM(MOD_LCTL | MOD_LSFT | MOD_LALT | MOD_LGUI)


