CONSOLE_ENABLE = no
COMMAND_ENABLE = no
MOUSEKEY_ENABLE = no
ORYX_ENABLE = yes
RGB_MATRIX_CUSTOM_KB = yes
SPACE_CADET_ENABLE = no
CAPS_WORD_ENABLE = yes
DYNAMIC_TAPPING_TERM_ENABLE = yes
LAYER_LOCK_ENABLE = yes

RGBLIGHT_ENABLE = no
RGB_MATRIX_ENABLE = yes
EEPROM_DRIVER = transient

DEBOUNCE_TYPE = asym_eager_defer_pk
OS_DETECTION_ENABLE = yes
KEY_OVERRIDE_ENABLE = yes
NKRO_ENABLE = yes

SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no 
MAGIC_ENABLE = no

LTO_ENABLE = yes
EXTRAFLAGS += -flto -O3
EXTRAFLAGS += -mcpu=cortex-m4
EXTRAFLAGS += -march=armv7e-m
EXTRAFLAGS += -mfpu=fpv4-sp-d16
EXTRAFLAGS += -mfloat-abi=hard
EXTRAFLAGS += -mthumb 
EXTRAFLAGS += -fsingle-precision-constant 



